# url: nailsea-bikers.io
# baseurl: /nailsea-bikers.io

url: https://nailseabikers.org.uk
baseurl: https://nailseabikers.org.uk

# Site settings
title: Nailsea Bikers
email: nailseabikers@hotmail.com
description: "Welcome to Nailsea Bikers and the home to the ‘Nailsea International Bike Show’."

# Google Analytics
google_analytics: UA-133651180-1

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/nailseabikers
  - title: facebook
    url: https://www.facebook.com/nailseabikers/

# Postal address (add as many lines as necessary)
address:
  - line: Nailsea
  - line: UK

# Build settings
markdown: kramdown
permalink: pretty

plugins:
  - jekyll-redirect-from
